title: Christopher Nguyen
email: cnguyen7@hawaii.edu
description: > # this means to ignore newlines until "baseurl:"
  Christopher Nguyen. UH Manoa '18. NASA Space Grant Fellow. Former Software Developer Intern at IBM and Oceanit. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrisnguyenhi.github.io" 
github_username: chrisnguyenhi
git_repo: chrisnguyenhi
github: https://github.com/chrisnguyenhi
linkedin: https://linkedin.com/in/chrisnguyenhi
projects: /projects
mail: mailto:cnguyen7@hawaii.edu

include: [_data]

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false

theme: minima 
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock


social:
  name: Christopher Nguyen
  links:
    - https://github.com/chrisnguyenhi

logo: /images/h.png
google_analytics: 